title: How to Graduate
lang: en
description: How to Graduate UW CEE grad school

remote_theme: rundocs/jekyll-rtd-theme@v1.1.7

addons_branch: true
edit: true

copyright:
  revision: true

addons:
  - github
  - i18n
  - plugins
  - analytics

# sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

# optional plugins
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
